# CMake generated Testfile for 
# Source directory: /home/at04/デスクトップ/ai-server-ssl-h/test
# Build directory: /home/at04/デスクトップ/ai-server-ssl-h/build/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(test/driver "test_driver")
set_tests_properties(test/driver PROPERTIES  _BACKTRACE_TRIPLES "/home/at04/デスクトップ/ai-server-ssl-h/test/CMakeLists.txt;21;add_test;/home/at04/デスクトップ/ai-server-ssl-h/test/CMakeLists.txt;0;")
add_test(test/filter/base "test_filter_base")
set_tests_properties(test/filter/base PROPERTIES  _BACKTRACE_TRIPLES "/home/at04/デスクトップ/ai-server-ssl-h/test/CMakeLists.txt;21;add_test;/home/at04/デスクトップ/ai-server-ssl-h/test/CMakeLists.txt;0;")
add_test(test/filter/state_observer/ball "test_filter_state_observer_ball")
set_tests_properties(test/filter/state_observer/ball PROPERTIES  _BACKTRACE_TRIPLES "/home/at04/デスクトップ/ai-server-ssl-h/test/CMakeLists.txt;21;add_test;/home/at04/デスクトップ/ai-server-ssl-h/test/CMakeLists.txt;0;")
add_test(test/filter/state_observer/robot "test_filter_state_observer_robot")
set_tests_properties(test/filter/state_observer/robot PROPERTIES  _BACKTRACE_TRIPLES "/home/at04/デスクトップ/ai-server-ssl-h/test/CMakeLists.txt;21;add_test;/home/at04/デスクトップ/ai-server-ssl-h/test/CMakeLists.txt;0;")
add_test(test/filter/va_calculator "test_filter_va_calculator")
set_tests_properties(test/filter/va_calculator PROPERTIES  _BACKTRACE_TRIPLES "/home/at04/デスクトップ/ai-server-ssl-h/test/CMakeLists.txt;21;add_test;/home/at04/デスクトップ/ai-server-ssl-h/test/CMakeLists.txt;0;")
add_test(test/game/action/with_planner "test_game_action_with_planner")
set_tests_properties(test/game/action/with_planner PROPERTIES  _BACKTRACE_TRIPLES "/home/at04/デスクトップ/ai-server-ssl-h/test/CMakeLists.txt;21;add_test;/home/at04/デスクトップ/ai-server-ssl-h/test/CMakeLists.txt;0;")
add_test(test/game/captain/detail/state "test_game_captain_detail_state")
set_tests_properties(test/game/captain/detail/state PROPERTIES  _BACKTRACE_TRIPLES "/home/at04/デスクトップ/ai-server-ssl-h/test/CMakeLists.txt;21;add_test;/home/at04/デスクトップ/ai-server-ssl-h/test/CMakeLists.txt;0;")
add_test(test/game/formation/halt "test_game_formation_halt")
set_tests_properties(test/game/formation/halt PROPERTIES  _BACKTRACE_TRIPLES "/home/at04/デスクトップ/ai-server-ssl-h/test/CMakeLists.txt;21;add_test;/home/at04/デスクトップ/ai-server-ssl-h/test/CMakeLists.txt;0;")
add_test(test/game/nnabla "test_game_nnabla")
set_tests_properties(test/game/nnabla PROPERTIES  _BACKTRACE_TRIPLES "/home/at04/デスクトップ/ai-server-ssl-h/test/CMakeLists.txt;21;add_test;/home/at04/デスクトップ/ai-server-ssl-h/test/CMakeLists.txt;0;")
add_test(test/logger "test_logger")
set_tests_properties(test/logger PROPERTIES  _BACKTRACE_TRIPLES "/home/at04/デスクトップ/ai-server-ssl-h/test/CMakeLists.txt;21;add_test;/home/at04/デスクトップ/ai-server-ssl-h/test/CMakeLists.txt;0;")
add_test(test/model/ball "test_model_ball")
set_tests_properties(test/model/ball PROPERTIES  _BACKTRACE_TRIPLES "/home/at04/デスクトップ/ai-server-ssl-h/test/CMakeLists.txt;21;add_test;/home/at04/デスクトップ/ai-server-ssl-h/test/CMakeLists.txt;0;")
add_test(test/model/command "test_model_command")
set_tests_properties(test/model/command PROPERTIES  _BACKTRACE_TRIPLES "/home/at04/デスクトップ/ai-server-ssl-h/test/CMakeLists.txt;21;add_test;/home/at04/デスクトップ/ai-server-ssl-h/test/CMakeLists.txt;0;")
add_test(test/model/field "test_model_field")
set_tests_properties(test/model/field PROPERTIES  _BACKTRACE_TRIPLES "/home/at04/デスクトップ/ai-server-ssl-h/test/CMakeLists.txt;21;add_test;/home/at04/デスクトップ/ai-server-ssl-h/test/CMakeLists.txt;0;")
add_test(test/model/geometry/box "test_model_geometry_box")
set_tests_properties(test/model/geometry/box PROPERTIES  _BACKTRACE_TRIPLES "/home/at04/デスクトップ/ai-server-ssl-h/test/CMakeLists.txt;21;add_test;/home/at04/デスクトップ/ai-server-ssl-h/test/CMakeLists.txt;0;")
add_test(test/model/geometry/point "test_model_geometry_point")
set_tests_properties(test/model/geometry/point PROPERTIES  _BACKTRACE_TRIPLES "/home/at04/デスクトップ/ai-server-ssl-h/test/CMakeLists.txt;21;add_test;/home/at04/デスクトップ/ai-server-ssl-h/test/CMakeLists.txt;0;")
add_test(test/model/obstacle/field "test_model_obstacle_field")
set_tests_properties(test/model/obstacle/field PROPERTIES  _BACKTRACE_TRIPLES "/home/at04/デスクトップ/ai-server-ssl-h/test/CMakeLists.txt;21;add_test;/home/at04/デスクトップ/ai-server-ssl-h/test/CMakeLists.txt;0;")
add_test(test/model/obstacle/robot "test_model_obstacle_robot")
set_tests_properties(test/model/obstacle/robot PROPERTIES  _BACKTRACE_TRIPLES "/home/at04/デスクトップ/ai-server-ssl-h/test/CMakeLists.txt;21;add_test;/home/at04/デスクトップ/ai-server-ssl-h/test/CMakeLists.txt;0;")
add_test(test/model/refbox "test_model_refbox")
set_tests_properties(test/model/refbox PROPERTIES  _BACKTRACE_TRIPLES "/home/at04/デスクトップ/ai-server-ssl-h/test/CMakeLists.txt;21;add_test;/home/at04/デスクトップ/ai-server-ssl-h/test/CMakeLists.txt;0;")
add_test(test/model/robot "test_model_robot")
set_tests_properties(test/model/robot PROPERTIES  _BACKTRACE_TRIPLES "/home/at04/デスクトップ/ai-server-ssl-h/test/CMakeLists.txt;21;add_test;/home/at04/デスクトップ/ai-server-ssl-h/test/CMakeLists.txt;0;")
add_test(test/model/updater/ball "test_model_updater_ball")
set_tests_properties(test/model/updater/ball PROPERTIES  _BACKTRACE_TRIPLES "/home/at04/デスクトップ/ai-server-ssl-h/test/CMakeLists.txt;21;add_test;/home/at04/デスクトップ/ai-server-ssl-h/test/CMakeLists.txt;0;")
add_test(test/model/updater/field "test_model_updater_field")
set_tests_properties(test/model/updater/field PROPERTIES  _BACKTRACE_TRIPLES "/home/at04/デスクトップ/ai-server-ssl-h/test/CMakeLists.txt;21;add_test;/home/at04/デスクトップ/ai-server-ssl-h/test/CMakeLists.txt;0;")
add_test(test/model/updater/refbox "test_model_updater_refbox")
set_tests_properties(test/model/updater/refbox PROPERTIES  _BACKTRACE_TRIPLES "/home/at04/デスクトップ/ai-server-ssl-h/test/CMakeLists.txt;21;add_test;/home/at04/デスクトップ/ai-server-ssl-h/test/CMakeLists.txt;0;")
add_test(test/model/updater/robot "test_model_updater_robot")
set_tests_properties(test/model/updater/robot PROPERTIES  _BACKTRACE_TRIPLES "/home/at04/デスクトップ/ai-server-ssl-h/test/CMakeLists.txt;21;add_test;/home/at04/デスクトップ/ai-server-ssl-h/test/CMakeLists.txt;0;")
add_test(test/model/updater/world "test_model_updater_world")
set_tests_properties(test/model/updater/world PROPERTIES  _BACKTRACE_TRIPLES "/home/at04/デスクトップ/ai-server-ssl-h/test/CMakeLists.txt;21;add_test;/home/at04/デスクトップ/ai-server-ssl-h/test/CMakeLists.txt;0;")
add_test(test/model/world "test_model_world")
set_tests_properties(test/model/world PROPERTIES  _BACKTRACE_TRIPLES "/home/at04/デスクトップ/ai-server-ssl-h/test/CMakeLists.txt;21;add_test;/home/at04/デスクトップ/ai-server-ssl-h/test/CMakeLists.txt;0;")
add_test(test/radio/connection/serial "test_radio_connection_serial")
set_tests_properties(test/radio/connection/serial PROPERTIES  _BACKTRACE_TRIPLES "/home/at04/デスクトップ/ai-server-ssl-h/test/CMakeLists.txt;21;add_test;/home/at04/デスクトップ/ai-server-ssl-h/test/CMakeLists.txt;0;")
add_test(test/radio/connection/udp "test_radio_connection_udp")
set_tests_properties(test/radio/connection/udp PROPERTIES  _BACKTRACE_TRIPLES "/home/at04/デスクトップ/ai-server-ssl-h/test/CMakeLists.txt;21;add_test;/home/at04/デスクトップ/ai-server-ssl-h/test/CMakeLists.txt;0;")
add_test(test/radio/grsim "test_radio_grsim")
set_tests_properties(test/radio/grsim PROPERTIES  _BACKTRACE_TRIPLES "/home/at04/デスクトップ/ai-server-ssl-h/test/CMakeLists.txt;21;add_test;/home/at04/デスクトップ/ai-server-ssl-h/test/CMakeLists.txt;0;")
add_test(test/radio/kiks "test_radio_kiks")
set_tests_properties(test/radio/kiks PROPERTIES  _BACKTRACE_TRIPLES "/home/at04/デスクトップ/ai-server-ssl-h/test/CMakeLists.txt;21;add_test;/home/at04/デスクトップ/ai-server-ssl-h/test/CMakeLists.txt;0;")
add_test(test/receiver/refbox "test_receiver_refbox")
set_tests_properties(test/receiver/refbox PROPERTIES  _BACKTRACE_TRIPLES "/home/at04/デスクトップ/ai-server-ssl-h/test/CMakeLists.txt;21;add_test;/home/at04/デスクトップ/ai-server-ssl-h/test/CMakeLists.txt;0;")
add_test(test/receiver/vision "test_receiver_vision")
set_tests_properties(test/receiver/vision PROPERTIES  _BACKTRACE_TRIPLES "/home/at04/デスクトップ/ai-server-ssl-h/test/CMakeLists.txt;21;add_test;/home/at04/デスクトップ/ai-server-ssl-h/test/CMakeLists.txt;0;")
add_test(test/util/adaptor "test_util_adaptor")
set_tests_properties(test/util/adaptor PROPERTIES  _BACKTRACE_TRIPLES "/home/at04/デスクトップ/ai-server-ssl-h/test/CMakeLists.txt;21;add_test;/home/at04/デスクトップ/ai-server-ssl-h/test/CMakeLists.txt;0;")
add_test(test/util/algorithm "test_util_algorithm")
set_tests_properties(test/util/algorithm PROPERTIES  _BACKTRACE_TRIPLES "/home/at04/デスクトップ/ai-server-ssl-h/test/CMakeLists.txt;21;add_test;/home/at04/デスクトップ/ai-server-ssl-h/test/CMakeLists.txt;0;")
add_test(test/util/kick/convert "test_util_kick_convert")
set_tests_properties(test/util/kick/convert PROPERTIES  _BACKTRACE_TRIPLES "/home/at04/デスクトップ/ai-server-ssl-h/test/CMakeLists.txt;21;add_test;/home/at04/デスクトップ/ai-server-ssl-h/test/CMakeLists.txt;0;")
add_test(test/util/math/affine "test_util_math_affine")
set_tests_properties(test/util/math/affine PROPERTIES  _BACKTRACE_TRIPLES "/home/at04/デスクトップ/ai-server-ssl-h/test/CMakeLists.txt;21;add_test;/home/at04/デスクトップ/ai-server-ssl-h/test/CMakeLists.txt;0;")
add_test(test/util/math/angle "test_util_math_angle")
set_tests_properties(test/util/math/angle PROPERTIES  _BACKTRACE_TRIPLES "/home/at04/デスクトップ/ai-server-ssl-h/test/CMakeLists.txt;21;add_test;/home/at04/デスクトップ/ai-server-ssl-h/test/CMakeLists.txt;0;")
add_test(test/util/math/detail/xyz "test_util_math_detail_xyz")
set_tests_properties(test/util/math/detail/xyz PROPERTIES  _BACKTRACE_TRIPLES "/home/at04/デスクトップ/ai-server-ssl-h/test/CMakeLists.txt;21;add_test;/home/at04/デスクトップ/ai-server-ssl-h/test/CMakeLists.txt;0;")
add_test(test/util/math/distance "test_util_math_distance")
set_tests_properties(test/util/math/distance PROPERTIES  _BACKTRACE_TRIPLES "/home/at04/デスクトップ/ai-server-ssl-h/test/CMakeLists.txt;21;add_test;/home/at04/デスクトップ/ai-server-ssl-h/test/CMakeLists.txt;0;")
add_test(test/util/math/geometry "test_util_math_geometry")
set_tests_properties(test/util/math/geometry PROPERTIES  _BACKTRACE_TRIPLES "/home/at04/デスクトップ/ai-server-ssl-h/test/CMakeLists.txt;21;add_test;/home/at04/デスクトップ/ai-server-ssl-h/test/CMakeLists.txt;0;")
add_test(test/util/math/geometry_traits "test_util_math_geometry_traits")
set_tests_properties(test/util/math/geometry_traits PROPERTIES  _BACKTRACE_TRIPLES "/home/at04/デスクトップ/ai-server-ssl-h/test/CMakeLists.txt;21;add_test;/home/at04/デスクトップ/ai-server-ssl-h/test/CMakeLists.txt;0;")
add_test(test/util/math/to_vector "test_util_math_to_vector")
set_tests_properties(test/util/math/to_vector PROPERTIES  _BACKTRACE_TRIPLES "/home/at04/デスクトップ/ai-server-ssl-h/test/CMakeLists.txt;21;add_test;/home/at04/デスクトップ/ai-server-ssl-h/test/CMakeLists.txt;0;")
add_test(test/util/net/multicast "test_util_net_multicast")
set_tests_properties(test/util/net/multicast PROPERTIES  _BACKTRACE_TRIPLES "/home/at04/デスクトップ/ai-server-ssl-h/test/CMakeLists.txt;21;add_test;/home/at04/デスクトップ/ai-server-ssl-h/test/CMakeLists.txt;0;")
add_test(test/util/time "test_util_time")
set_tests_properties(test/util/time PROPERTIES  _BACKTRACE_TRIPLES "/home/at04/デスクトップ/ai-server-ssl-h/test/CMakeLists.txt;21;add_test;/home/at04/デスクトップ/ai-server-ssl-h/test/CMakeLists.txt;0;")
